[package]
name = "capbac-ruby"
version = "0.1.0"
authors = ["Kirill Chernyshov <delaguardo@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rutie = "0.6.1"
url = "2.1"
openssl = "0.10"
lazy_static = "1"
protobuf = "~2"
capbac = "0.1.0"