[package]
name = "capbac-ruby"
version = "0.2.0"
authors = ["Kirill Chernyshov <delaguardo@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rutie = "0.8.0"
url = "2.1"
openssl = "0.10"
ring = "0.16.15"
lazy_static = "1"
protobuf = "2.16.2"
capbac = "0.2.1"