# frozen_string_literal: true

require 'rubygems/tasks'
require 'thermite/tasks'

Gem::Tasks.new

Thermite::Tasks.new

desc 'Run Rust & Ruby testsuites'
task test: ['thermite:build', 'thermite:test'] do
end
